services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: ai_safebuild_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: ai_safebuild_frontend
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8000